### ISSUE TITLE
Failed to work with Crossover 21.2

### ISSUE THREAD

**Issue by ajtazer** [AdityaDargan/JEE-MAINS-RESULT-FINDER#4]
ik its not created to work on MacOS but still, i tried to run it via a Virtualization Wine Software called CrossOver, and it gave the Error shown below
<img width="549" alt="image" src="https://user-images.githubusercontent.com/37796611/184598433-45ee5c18-2b89-4708-a870-c9245d45f677.png">
tell me if it can be fixed by a few tweaks so that i can run it on my mac or not.
Kudos to ur Efforts 🎊

**Comment by AdityaDargan** [comment]
Hi Anuj, thanks for providing your feedback.
I believe it should run on the wine software, but while selecting the exe
file make sure to select the initial one and see if everything is getting
extracted correctly, and if that doesn't work then you can try to run it on
a virtual machine.
As we are getting a filenotfound error so that maybe due to all files not
getting extracted properly or you're just running a single exe file and its
path or other dependencies can't be used.

**Comment by ajtazer** [comment]
Sorry, i cant make sure that setup extracted each and every dependency or not, but i made sure the setup finished without throwing any error. 
Wine is a Headache, will have to use VM 😵‍💫..
Thanks for reply

**Comment by AdityaDargan** [comment]
Yeah install it on a vm and do let me know if it works.
Thank you
